name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]  # Adjust this as necessary for other versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python and cache pip
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enabling built-in pip caching

    - name: Cache Python environment
      uses: actions/cache@v3.2.4
      id: env-cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pythonenv-${{ matrix.python-version }}-${{ hashFiles('rag/requirements.txt') }}

    - name: Install pip dependencies
      if: steps.env-cache.outputs.cache-hit != 'true'
      run: |
        pip install -r rag/requirements.txt

    - name: Cache pytest artifacts
      uses: actions/cache@v3.2.4
      with:
        path: .pytest_cache
        key: ${{ runner.os }}-pytest-${{ github.sha }}

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest tests --capture=no  # Disable capturing to allow live logging
